### ISSUE TITLE
Assistance Required: Installation Error of MadAnalysis5 in MG5_aMC_v3_5_5 on Ubuntu 22.04.4 LTS with ROOT 6.30/08

### ISSUE THREAD

**Issue by DorrFlower** [MadAnalysis/madanalysis5#261]
### Question

Dear MadGraph5_aMC@NLO Development Team,

I encountered an installation error while trying to install MadAnalysis5 using the MG5_aMC_v3_5_5 framework on Ubuntu with ROOT version 6.30/08. The standard installation procedures did not resolve the issue, resulting in a compilation error.

The error messages from the log are as follows:

MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /home/dorr/Downloads/MG5_aMC_v3.5.5/MG5_aMC_v3_5_5/HEPTools/madanalysis5/madanalysis5/tools/SampleAnalyzer/Interfaces/compilation_root.log
MA5-ERROR: The library building aborted.

DEBUG:  return_code =  9 [madgraph_interface.py at line 6146]
Default installation of Madanalysis5 failed, we suggest you try again with the options '--no_MA5_further_install --no_root_in_MA5'.
Command "install MadAnalysis5" interrupted with error:
InvalidCmd : Installation of madanalysis5 failed.

Attached is the 'MG5_debug' file with detailed error information for troubleshooting.

A solution or workaround would be appreciated.

Best,
Dorr

[MG5_debug.txt](https://github.com/user-attachments/files/16919259/MG5_debug.txt)

**Comment by BFuks** [comment]
Dear Dorr,

The debug file is not very enlightening I am afraid... Can you please try to install MadAnalysis directly, as a standalone package and using the latest version. Then, please let me know whether this solves all issues. Thanks in advance.

Cheers,

Benjamin

**Comment by DorrFlower** [comment]
Dear Professor Fuks,

I've installed MadAnalysis 5 (version 1.10.16) on Ubuntu 22.04 and encountered an issue. Here's what happened:

1. Running `./bin/ma5` resulted in:
   ```
   /usr/bin/env: ‘python’: No such file or directory
   ```

2. Trying `python ./bin/ma5` gave:
   ```
   Command 'python' not found, did you mean:
   command 'python3' from deb python3
   command 'python' from deb python-is-python3
   ```

3. Using `python3 ./bin/ma5` led to:
   ```
   AttributeError: module 'importlib' has no attribute 'util'
   ```

Python 3.10.12 is installed, and I'm using the standard GCC compiler.

Any help with this would be appreciated.

Best,
Dorr

**Comment by BFuks** [comment]
Hi Dorr,

Creating a virtual link connecting with python referring to python3 should fix the issues 1 and 2. For the issue 3, please check:
  https://github.com/MadAnalysis/madanalysis5/issues/237
Note that we are preparing a major release in a couple of weeks where this will be fixed.

Best regards,

Benjamin
